package com.hu.brg.define.application.save;

import com.hu.brg.define.domain.Attribute;
import com.hu.brg.define.domain.AttributeValue;

public class AttributeValueSaveBuilder {

    /**
     * Auto generated by Intellij
     */

    private Attribute attribute;
    private String value;
    private String valueType;
    private int order;
    private boolean isLiteral;
    private int id;

    public AttributeValueSaveBuilder setAttribute(Attribute attribute) {
        this.attribute = attribute;
        return this;
    }

    public AttributeValueSaveBuilder setValue(String value) {
        this.value = value;
        return this;
    }

    public AttributeValueSaveBuilder setValueType(String valueType) {
        this.valueType = valueType;
        return this;
    }

    public AttributeValueSaveBuilder setOrder(int order) {
        this.order = order;
        return this;
    }

    public AttributeValueSaveBuilder setLiteral(boolean literal) {
        isLiteral = literal;
        return this;
    }

    public AttributeValueSaveBuilder setId(int id) {
        this.id = id;
        return this;
    }

    public AttributeValue build() {
        return new AttributeValue(id, attribute, value, valueType, order, isLiteral);
    }
}
